# Specify, that we want to use docker in the docker :)
services:
  - docker
  
before_install:
- docker pull ghdl/ghdl:stretch-mcode
  
# Here are the list of run scripts of different DUTs/testcases
script:
    # Testing the installation of the ghdl
  - docker run -t ghdl/ghdl:stretch-mcode ghdl --version
  
    # Mount the repo to docker, and run the hello world example
  - > 
    docker run -t -v `pwd`:/mnt/data ghdl/ghdl:stretch-mcode
    /bin/bash -c  "chmod u+x /mnt/data/hello_world/hello_world.sh;
    /mnt/data/hello_world/hello_world.sh"
    
    # Mount the repo to docker, and run the adder example
  - >
    docker run -t -v `pwd`:/mnt/data ghdl/ghdl:stretch-mcode
    /bin/bash -c  "chmod u+x /mnt/data/adder/adder.sh;
    /mnt/data/adder/adder.sh"
